osx_image: xcode7.2
language: objective-c

jdk:
  - oraclejdk8

install:
  - mvn install:install-file -Dfile=lib/face/opencv-2412.jar -DgroupId=org.opencv -DartifactId=opencv -Dversion=2.4.12 -Dpackaging=jar
  - ./travis/travis-ingestor-files.sh
  - ./travis/travis-install-archivist-sdk.sh
  - ./travis/travis-install-archivist.sh

script:
  - mvn integration-test

notifications:
  slack: zorroa:U0489fQGuSPls5EZZfSUoGsL

