osx_image: xcode7.2
language: objective-c

jdk:
  - oraclejdk8

install:
  - ./travis/travis-ingestor-files.sh
  - ./travis/travis-install-archivist-sdk.sh
  - ./travis/travis-install-archivist.sh

script:
  - mvn integration-test

notifications:
  slack: zorroa:U0489fQGuSPls5EZZfSUoGsL

