
#
# Spring and Spring Boot Settings
#
server:
    port: 8066

flyway:
    check-location: true
    initOnMigrate: true

logging:
    level:
        com:
            googlecode:
                flyway: "DEBUG"

#security:
#    basic:
#        enabled: false

#
# Archivist Settings
#
archivist:
    datasource:
        primary:
            url: "jdbc:h2:./db/archivist;DB_CLOSE_DELAY=-1;MODE=Oracle;"
            driver-class-name: "org.h2.Driver"
            username: "sa"
            password: ""
    events:
        port: 8087

    index:
        alias: "archivist"
    proxies:
        basePath: "proxies"
        format: "jpg"
    ingest:
        ingestWorkers: 1
    export:
        autoStart: true
        basePath: "exports"
        maxAssetCount: 1024
        maxTotalFileSize: "500M"
    snapshot:
        basePath: "snapshots"
        repoName: "backups"

