
#
# HTTP Port
#
server:
    port: 8066

security:
    basic:
        enabled: false

#
# Archivist Settings
#
archivist:
    index:
        alias: "archivist"
    proxies:
        path: "proxies"
        format: "png"
        scales: [ 0.25 ]

