
#
# HTTP Port
#
server:
    port: 8066

#security:
#    basic:
#        enabled: false

#
# Archivist Settings
#
archivist:
    index:
        alias: "archivist"
    proxies:
        basePath: "proxies"
        format: "png"


