
#
# Spring and Spring Boot Settings
#
server:
    port: 8066

spring:
    datasource:
        url: "jdbc:h2:./archivist;DB_CLOSE_DELAY=-1;MODE=Oracle;"
        driver-class-name: "org.h2.Driver"

#security:
#    basic:
#        enabled: false

#
# Archivist Settings
#
archivist:
    events:
        port: 8087

    index:
        alias: "archivist"
    proxies:
        basePath: "proxies"
        format: "png"
    ingest:
        ingestWorkers: 1
    snapshot:
        basePath: "snapshots"
        repoName: "backups"

