
#
# HTTP Port
#
server:
    port: 8066


spring:
    datasource:
        url: "jdbc:h2:mem:archivist;DB_CLOSE_DELAY=-1;MODE=Oracle;"
        driver-class-name: "org.h2.Driver"

#security:
#    basic:
#        enabled: false

#
# Archivist Settings
#
archivist:
    index:
        alias: "archivist"
    proxies:
        basePath: "proxies"
        format: "png"


