server:
  port: 9090

spring:
  flyway:
    schemas: zorroa
  datasource:
    url: jdbc:postgresql://localhost:5432/zorroa?currentSchema=zorroa
    username: zorroa
    password: zorroa
    driver-class-name: org.postgresql.Driver

security:
    admin-key: classpath:admin-key.json