language: java

services:
  - docker

install:
  - cd es-similarity
  - mvn package
  - cd ../
  - cp es-similarity/target/releases/es-similarity.zip elasticsearch
  - docker-compose up -d
  - ./travis/travis-install-test-data.sh

script:
  - mvn test

notifications:
  slack: zorroa:U0489fQGuSPls5EZZfSUoGsL
 