
version: '3'
services:

  # Elastic Search instance used for local devlopment servers.
  es:
    image: "zorroa-elasticsearch-single:latest"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      discovery.type: "single-node"

  # Elastic Search instance used for unit tests
  es-test:
    image: "zorroa-elasticsearch-single:latest"
    ports:
      - "39200:9200"
      - "39300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      discovery.type: "single-node"

  # Postgres instance used for local devleopment servers.
  postgres:
    image: "postgres:9.6.9"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: zorroa
      POSTGRES_USER: zorroa
      POSTGRES_DB: zorroa
      PGDATA: /var/lib/postgresql/data/pgdata

