
version: '3'
services:

  ## Unit testing services.

  # Elastic Search instance used by the unit tests.
  test-es:
    build:
      context: elasticsearch
      args:
        node_type: single
    ports:
      - "39200:9200"
      - "39300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"

  # Postgres instance used by the unit tests.
  test-postgres:
    image: "postgres:9.6.9"
    hostname: "localhost"
    ports:
     - "35432:5432"
    environment:
      POSTGRES_PASSWORD: zorroa
      POSTGRES_USER: zorroa
      POSTGRES_DB: zorroa

  ## Local Development Services

  # Elastic Search instance used for local devlopment servers.
  es:
    build:
      context: elasticsearch
      args:
        node_type: single
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"

  # Postgres instance used for local devleopment servers.
  postgres:
    image: "postgres:9.6.9"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: zorroa
      POSTGRES_USER: zorroa
      POSTGRES_DB: zorroa
      PGDATA: /var/lib/postgresql/data/pgdata

  # Local Archivist server.
  archivist:
    links:
       - "es"
       - "postgres"
    build:
      context: archivist
    ports:
      - 8080:8080
    volumes:
      - "./localdev/shared:/shared"
      - "./localdev/zorroa-archivist-config:/config"
      - "./archivist/target:/service"
      - "../zorroa-test-data:/zorroa-test-data"
    environment:
      ZORROA_USER: admin

  # Local Archivist server.
  analyst:
    image: "zorroa/sdk:latest"
    links:
       - "archivist"
    ports:
      - 5000:5000
    volumes:
      - "./localdev/shared:/shared"
      - "../zorroa-test-data:/zorroa-test-data"

  curator:
     image: "zorroa-js-curator"
     user: node
     ports:
       - 80:8081
       - 443:8443
     environment:
         NODE_ENV: "production"
         ARCHIVIST_API_URL: "http://archivist:8080"
         CURATOR_PORT_SECURE: "8443"

