version: "3.6"
services:
  es1:
    build:
      context: services/elasticsearch
      args:
        node_type: single

  api-gateway:
    build:
      context: services/api-gateway

  auth-server:
    depends_on:
      - zmlp-jvm-common
    build:
      context: services/auth-server

  archivist:
    depends_on:
      - zmlp-jvm-common
    build:
      context: services/archivist

  officer:
    depends_on:
      - zmlp-jvm-common
    build:
      context: services/officer

  analyst:
    build:
      context: services/analyst

  wallet:
    build:
      context: .
      dockerfile: applications/wallet/Dockerfile
      args:
        CI_COMMIT_SHA: $CI_COMMIT_SHA

  zmlp-jvm-common:
    image: zmlp/jvm-common:development
    command: echo
    build:
      context: lib/jvm-common

  zmlp-py3-base:
    build:
      context: containers/zmlp-py3-base

  zmlp-py3-client:
    depends_on:
      - zmlp-py3-base
    build:
      context: client/python

  zmlp-py3-sdk:
    depends_on:
      - zmlp-py3-client
    build:
      context: sdk

  zmlp-plugins-base:
    depends_on:
      - zmlp-py3-sdk
    build:
      context: containers/zmlp-plugins-base

  zmlp-plugins-core:
    depends_on:
      - zmlp-plugins-base
    build:
      context: containers/zmlp-plugins-core

  zmlp-plugins-analysis:
    depends_on:
      - zmlp-plugins-base
    build:
      context: containers/zmlp-plugins-analysis
