
version: '3'
services:

  ## Unit testing services.

  # Elastic Search instance used by the unit tests.
  test-es:
    build:
      context: elasticsearch
      args:
        node_type: single
    ports:
      - "39200:9200"
      - "39300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"

  # Elastic Search instance used for local devlopment servers.
  es:
    build:
      context: elasticsearch
      args:
        node_type: single
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"

  # Postgres instance used for local development servers.
  postgres:
    image: "postgres:9.6.9"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: zorroa
      POSTGRES_USER: zorroa
      POSTGRES_DB: zorroa
      PGDATA: /var/lib/postgresql/data/pgdata

  # Local Archivist server.
  archivist:
    links:
       - "es"
       - "postgres"
    build:
      context: archivist
    ports:
      - 8080:8080
    volumes:
      - "./localdev/shared:/shared"
      - "./localdev/zorroa-archivist-config:/config"
      - "./archivist/target:/service"
      - "../zorroa-test-data:/zorroa-test-data"

  # Local Archivist server.
  analyst:
    build: ../zorroa-plugin-sdk
    links:
       - "archivist"
    ports:
      - 5000:5000
    volumes:
      - "./localdev/shared:/shared"
      - "../zorroa-test-data:/zorroa-test-data"

  curator:
     build: ../zorroa-js-curator
     user: node
     ports:
       - 80:8081
       - 443:8443
     environment:
         NODE_ENV: "production"
         ARCHIVIST_API_URL: "http://archivist:8080"
         CURATOR_PORT_SECURE: "8443"

