
version: '3.6'
services:

  ## Unit testing services.

  # Elastic Search instance used for local development servers.
  es1:
    build:
      context: ../services/elasticsearch
      args:
        node_type: single
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: "single-node"
      discovery.zen.minimum_master_nodes: "1"
      cluster.name: "zorroa-es-cluster"
      network.host: "0.0.0.0"
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"

  # Postgres instance used for local development servers.
  postgres:
    image: "postgres:9.6.9"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: zorroa
      POSTGRES_USER: zorroa
      POSTGRES_DB: zorroa
      PGDATA: /var/lib/postgresql/data/pgdata

  redis:
    image: redis:alpine
    ports:
       - 6379:6379

  minio:
    image: "minio/minio"
    ports:
      - "9000:9000"
    command: server /data
    environment:
      MINIO_ACCESS_KEY: qwerty123
      MINIO_SECRET_KEY: 123qwerty

  # Auth server
  auth-server:
    links:
       - "postgres"
    build:
      context: ../services/auth-server
    ports:
      - 9090:9090
    volumes:
      - "./config/auth-server:/config"
      - "./config/keys/inception-key.json:/config/inception-key.json"

  # Local Archivist server.
  archivist:
    links:
       - "es1"
       - "postgres"
       - "auth-server"
    environment:
      SENTRY_ENVIRONMENT: localdev
      ARCHIVIST_STORAGE_ACCESSKEY: qwerty123
      ARCHIVIST_STORAGE_SECRETKEY: 123qwerty
      ARCHIVIST_STORAGE_URL: http://minio:9000
    build:
      context: ../services/archivist
    ports:
      - 8080:8080
    volumes:
      - "./config/monitoring:/monitoring"
      - "./config/archivist:/config"
      - "./config/keys/inception-key.json:/config/inception-key.json"

  analyst:
    links:
       - "archivist"
    build:
      context: ../services/analyst
    ports:
      - 5000:5000
    volumes:
       - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      PIXML_SERVER: http://archivist:8080

volumes:
  zmlp-config:
    external: true
