
version: '3.6'
services:

  ## Unit testing services.

  # Elastic Search instance used for local development servers.
  es:
    build:
      context: elasticsearch
      args:
        node_type: single
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: "single-node"
      discovery.zen.minimum_master_nodes: "1"
      cluster.name: "zorroa-es-cluster"
      network.host: "0.0.0.0"
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"

  # Postgres instance used for local development servers.
  postgres:
    image: "postgres:9.6.9"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: zorroa
      POSTGRES_USER: zorroa
      POSTGRES_DB: zorroa
      PGDATA: /var/lib/postgresql/data/pgdata

  redis:
    image: redis:alpine
    ports:
       - 6379:6379

  # Local Archivist server.
  archivist:
    links:
       - "es"
       - "postgres"
    build:
      context: archivist
    ports:
      - 8080:8080
    volumes:
      - "./archivist/localdev/shared:/shared"
      - "./archivist/localdev/monitoring:/monitoring"
      - "./archivist/localdev/zorroa-archivist-config:/config"
      - "../zorroa-test-data:/zorroa-test-data"

secrets:
  prometheus.yml:
    file: ./localdev/monitoring/prometheus.yml
