wallet-frontend-test-suite:
  image: node:12
  stage: test
  only:
    refs:
      - merge_requests
      - development
    changes:
      - applications/wallet/app/frontend/**/*
  before_script:
    - cd applications/wallet/app/frontend
    - npm ci
  script:
    - npm run lint
    - npm run test:cover
    - npm run size
