image: node:12

before_script:
  - cd applications/wallet/app/frontend
  - npm ci

wallet-frontend-test-suite:
  stage: test
  only:
    refs:
      - merge_requests
      - development
    changes:
      - applications/wallet/app/frontend/**/*
  script:
    - npm run lint
    - npm run test:cover
    - npm run size
