image: node:12

stages:
  - test
  - build
  - push
  - deploys

lint:
stage: test
script:
  - npm install
  - npx eslint ./ --quiet
  - npx stylelint '**/*.scss'

unit_test:
  stage: test
  script:
    - npm install
    - TZ=UTC npx jest --bail --silent --ci