server:
  port: 9090

spring:
  profiles:
    active: aws
  flyway:
    schemas: auth
  datasource:
    url: jdbc:postgresql://localhost:5432/zorroa?currentSchema=auth
    username: zorroa
    password: zorroa
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 4
  main:
    allow-bean-definition-overriding: true

zmlp:
  security:
    inception-key: /service/config/inception-key.json
  storage:
    system:
      access-key: qwerty123
      secret-key: 123qwerty
      url: http://minio:9000
      bucket: system-storage
      create-bucket: false

management:
  metrics:
    tags:
      application: auth-server
    export:
      prometheus:
        enabled: true
  health:
    status:
      http-mapping:
        DOWN: 400
  endpoints:
    password: ${random.value}
    web:
      exposure:
        include: metrics,info,health,prometheus
      base-path: /monitor

#Swagger info
swagger:
  isPublic: true
  title: ZMLP APIKey Server
  description: Validates ZMLP API keys
  version: 1.0.0

  termOfService: http://www.zorroa.com/terms

  contactCompanyName: Zorroa
  contactCompanyWebsite: http://www.zorroa.com/contact
  contactCompanySupportEmail: support@zorroa.com
  restBasePackage: com.zorroa.auth.rest
  licenseName: Commercial
  licenseUrl: http://www.zorroa.com/contact
