.dockerhub-build-push:
  image: boonai/docker-buildx
  stage: push
  services:
    - docker:19-dind
  variables:
    FF_USE_LEGACY_KUBERNETES_EXECUTION_STRATEGY: "false" # This feature flag fixes a bug where the job would stop and say it succeeded.
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://localhost:2375
    SOURCE_TAG: latest
    DOCKER_TAG: test #TODO: CHANGE ME
    CONTAINERS: none
  retry: 2
  before_script:
    - apk add docker-compose
    - docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_PASS"
  script:
    - ./buildx -t 1 ${CONTAINERS}
    - for c in ${CONTAINERS}; do docker tag boonai/$c:${SOURCE_TAG} boonai/$c:${DOCKER_TAG}; done
    - for c in ${CONTAINERS}; do docker push boonai/$c:${DOCKER_TAG}; done

kotlin-services-build-push-latest:
  extends: .dockerhub-build-push
  variables:
    CONTAINERS: elasticsearch jvm-common archivist authserver officer
#  rules:
#    # Scheduled Pipelines
#    - if: '$CI_PIPELINE_SOURCE == "schedule"'
#      when: never
#    # Merged to development with Boon AI changes
#    - if: $CI_COMMIT_BRANCH == "development"
#      changes:
#        - "services/jvm-common/**/*"
#        - "services/archivist/**/*"
#        - "services/auth-server/**/*"
#        - "services/elasticsearch/**/*"
#        - "services/officer/**/*"

python-services-build-push-latest:
  extends: .dockerhub-build-push
  variables:
    CONTAINERS: >
      reporter plugins-train ml-bbq analyst plugins-analysis plugins-models plugins-core
      boondocks boonflow boonlab boonsdk py3-base
#  rules:
#    # Scheduled Pipelines
#    - if: '$CI_PIPELINE_SOURCE == "schedule"'
#      when: never
#    # Merged to development with Boon AI changes
#    - if: $CI_COMMIT_BRANCH == "development"
#      changes:
#        - "client/**/*"
#        - "containers/**/*"
#        - "services/analyst/**/*"
#        - "services/mlbbq/**/*"

wallet-build-push-latest:
  extends: .dockerhub-build-push
  variables:
    CONTAINERS: wallet
#  rules:
#    # Scheduled Pipelines
#    - if: '$CI_PIPELINE_SOURCE == "schedule"'
#      when: never
#    # Merged to Development with Wallet changes
#    - if: $CI_COMMIT_BRANCH == "development"
#      changes:
#        - "applications/wallet/**/*"

metrics-build-push-latest:
  extends: .dockerhub-build-push
  variables:
    CONTAINERS: metrics
#  rules:
#    # Scheduled Pipelines
#    - if: '$CI_PIPELINE_SOURCE == "schedule"'
#      when: never
#    # Merged to Development with Wallet changes
#    - if: $CI_COMMIT_BRANCH == "development"
#      changes:
#        - "services/metrics/**/*"

api-gateway-build-push-latest:
  extends: .dockerhub-build-push
  variables:
    CONTAINERS: apigateway
#  rules:
#    # Scheduled Pipelines
#    - if: '$CI_PIPELINE_SOURCE == "schedule"'
#      when: never
#    # Merged to Development with Wallet changes
#    - if: $CI_COMMIT_BRANCH == "development"
#      changes:
#        - "services/api-gateway/**/*"

