## Metrics Backend Tests
metrics-backend-test-suite:
  stage: test
  image: mc706/pipenv-3.7
  services:
      - name: postgres:9.6.9
        alias: postgres
  variables:
    DJANGO_SETTINGS_MODULE: metrics.settings.testing
    DEBUG: "true"
    PG_DB_HOST: postgres
    PG_DB_USER: metrics
    PG_DB_PASSWORD: 2mAPDWhuiYdIW69u
    POSTGRES_DB: metrics
    POSTGRES_USER: metrics
    POSTGRES_PASSWORD: 2mAPDWhuiYdIW69u

  script:
    - cd services/metrics
    - pipenv sync
    - cd app
    - pipenv run flake8
    - pipenv run pytest --cov=.
  rules:
    # Scheduled Pipelines
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    # MR to any branch that is not master with Backend changes
    - if: $CI_MERGE_REQUEST_IID && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "master"
      changes:
        - "services/metrics/app/**/*"
    # MR to QA with any change
    - if: $CI_MERGE_REQUEST_IID && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "qa"
      changes:
        - "**/*"
    # Merged to Development with Backend changes
    - if: $CI_COMMIT_BRANCH == "development"
      changes:
        - "services/metrics/app/**/*"
    # Merged to QA with any change
    - if: $CI_COMMIT_BRANCH == "qa"
      changes:
        - "**/*"

## Metrics Build & Push Latest on changes to Development
metrics-dockerhub-build-push-latest:
  image: boonai/docker-buildx
  stage: push
  services:
    - docker:19-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_TAG: latest
  retry: 2
  before_script:
    - apk add docker-compose
    - docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_PASS"
  script:
    - ./buildx metrics
    - docker tag boonai/metrics:latest boonai/metrics:${DOCKER_TAG}
    - docker push boonai/metrics:${DOCKER_TAG}
  rules:
    # Scheduled Pipelines
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    # Merged to Development with Metrics changes
    - if: $CI_COMMIT_BRANCH == "development"
      changes:
        - "services/metrics/**/*"

## Metrics Build & Push QA on changes to QA branch
metrics-dockerhub-build-push-qa:
  extends:
    - metrics-dockerhub-build-push-latest
  variables:
    DOCKER_TAG: qa
  rules:
    # Merged to QA with any change
    - if: $CI_COMMIT_BRANCH == "qa"
      changes:
        - "**/*"

## Metrics Deploy Latest on any changes to Development
metrics-deploy-development:
  image: google/cloud-sdk
  retry: 1
  variables:
    PROJECT: zvi-dev
  stage: deploy
  environment:
    name: dev
    url: https://dev.console.zvi.zorroa.com/
  before_script:
    - echo $DEV_SA_JSON > ./sa.json
    - gcloud auth activate-service-account $SA_EMAIL --key-file=./sa.json
    - gcloud container clusters get-credentials zmlp --zone us-central1-a --project ${PROJECT}
  script:
    - kubectl --namespace default rollout restart deployment metrics
  rules:
    # Scheduled Pipelines
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    # Merged to development with Metrics changes
    - if: $CI_COMMIT_BRANCH == "development"
      changes:
        - "services/metrics/**/*"

## Metrics Deploy Latest on any changes to QA
metrics-deploy-qa:
  extends:
    - metrics-deploy-development
  variables:
    PROJECT: zvi-qa
  environment:
    name: qa
    url: https://qa.console.zvi.zorroa.com/
  before_script:
    - echo $QA_SA_JSON > ./sa.json
    - gcloud auth activate-service-account $SA_EMAIL --key-file=./sa.json
    - gcloud container clusters get-credentials zmlp --zone us-central1-a --project ${PROJECT}
  rules:
    # Merged to QA with any change
    - if: $CI_COMMIT_BRANCH == "qa"
      changes:
        - "**/*"
